### ISSUE TITLE
Unable to interrupt U-Boot menu with bootcount=0

### ISSUE THREAD

**Issue by ndoo** [noblepepper/Das-U-boot#2]
Potentially causes soft brick if OpenWrt/LEDE does not boot (have to use a SPI programmer to erase U-Boot environment).

Could implement/allow U-Boot's built in logic to check for break/Ctrl+C even with bootcount=0 or maybe immediately go to Option 4 (U-Boot command line) if GPIO 46 is HIGH to prevent such a situation.

**Comment by noblepepper** [comment]
bootcount is not used to set the timing for option selection but setting _bootdelay_ to 0 will cause the condition you describe so DON'T DO IT!

It will be awhile before I get time to work on Das-U-Boot again, it is now shipping burned on the hardware I was targeting. If you develop a fix in the mean time **I will be more than happy to get a pull request** though, if not I'll definitely implement something the next time I work on it.

A simpler approach than using a gpio would be to set timer1 to 1 if the environment variable is less than 1 thus always giving at least one second opportunity for the user to enter a selection.

If you do use a gpio be aware that he hardware needs a pull up or down on it or noise will cause problems. 

If you use the same gpio as the web/usb load is triggered by please make sure it doesn't interfere with those functions. I intentionally set this up so the user can hold a button while applying power then release it at the appropriate time to trigger a web/usb load. This is much more convenient when using a jumper instead of a button, plug in the jumper, power up, remove jumper at the correct time to trigger the load. Maybe use 9-12 seconds to trigger the menu mode?

**Comment by ndoo** [comment]
Sorry I meant bootdelay not bootcount. Alright, will do something about it,
once I order more VoCore2s (my other PCBs are beta boards)

**Comment by noblepepper** [comment]
I didn't know what hardware you were on, yes this is on the VoCore2. 

From the behaviour with the GD32 USB/UART (on Ultimate and Airplay versions) Vonger definitely has done something to alter the behavior of u-boot. I'm not sure what, but changing something in Das-U-boot  is a definite possibility. In any case until he updates his github repo, make a backup copy of what comes on the VoCore2 in case of problems

**Comment by ndoo** [comment]
Yes I am using it on VoCore2 as well. Now I'm unable to reflash my VoCore2
to a working LEDE build because I was experimenting with the DTS files and
broke boot.

It's fine, I have an SPI flasher :)

**Comment by noblepepper** [comment]
Actually I should have said the release version VoCore2's have my u-boot, my beta came with the mediatek sdk u-boot on it.

Either should use compiled in defaults if the checksum on uboot-env doesn't come out right, you can either zero that partition or just write a byte or two to inside uboot-env.
